# Generated by Django 5.2.11 on 2026-03-23 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_offer_matched_user_session_offer_matchrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefers_online', models.BooleanField(default=True)),
                ('prefers_inperson', models.BooleanField(default=False)),
                ('availability', models.CharField(blank=True, max_length=200)),
                ('safety_notes', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
