# Generated by Django 5.2.11 on 2026-04-01 21:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill_tags_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('giver', 'receiver')},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='matchrequest',
            name='used_smart_matching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='match_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.matchrequest'),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='multiple_sessions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='prefers_inperson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='prefers_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='suggested_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='suggested_location_or_platform',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cultural_skills_wanted',
            field=models.ManyToManyField(blank=True, related_name='cultural_wanting_users', to='core.skill'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_smart_matching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interested_in_cultural_exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userskill',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True),
        ),

        # FIXED: remove invalid datetime default from ForeignKey
        migrations.AlterField(
            model_name='session',
            name='offer',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.offer'),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(max_length=50),
        ),

        # FIX 1: Drop NOT NULL so we can clean the data
        migrations.RunSQL(
            "ALTER TABLE core_userprofile ALTER COLUMN availability DROP NOT NULL;"
        ),

        # FIX 2: Clean invalid JSON values
        migrations.RunSQL(
            "UPDATE core_userprofile SET availability = NULL WHERE availability IS NOT NULL;"
        ),

        # FIX 3: Now safely convert to JSONField
        migrations.AlterField(
            model_name='userprofile',
            name='availability',
            field=models.JSONField(blank=True, null=True),
        ),

        migrations.RemoveField(
            model_name='rating',
            name='session',
        ),
    ]
