# Generated by Django 5.2.11 on 2026-04-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_culturalconnectionrequest_message_cultural_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cultural_interest_other',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
