# Generated by Django 5.2.11 on 2026-04-17 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_cultural_interest_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cultural_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.culturalconnectionrequest'),
        ),
        migrations.AlterField(
            model_name='session',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.offer'),
        ),
    ]
